name: "Setup canary ndk"
description: "Sets up canary ndk"
outputs:
  ndk-path:
    value: ${{ steps.path.outputs.path }}
    description: "Output path of the ndk"
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}
    description: "Whether a cache hit occurred for the ndk"
runs:
  using: "composite"
  steps:
    - name: Get Home dir
      id: home-dir
      run: echo "path=${HOME}" >> ${GITHUB_OUTPUT}
      shell: bash

    - name: NDK cache
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.home-dir.outputs.path }}/android-ndk-r27-canary/
        key: ${{ runner.os }}-ndk-r27-canary

    - name: Download canary ndk
      if: ${{ !steps.cache.outputs.cache-hit }}
      env:
        CANARY_URL: https://github.com/QuestPackageManager/ndk-canary-archive/releases/download/27.0.1/android-ndk-10883340-linux-x86_64.zip
      run: wget ${CANARY_URL} -O ${HOME}/ndk.zip
      shell: bash

    - name: Unzip ndk
      if: ${{ !steps.cache.outputs.cache-hit }}
      run: 7z x "${HOME}/ndk.zip" -o"${HOME}/"
      shell: bash

    - name: Set output
      id: path
      shell: bash
      run: echo "path=${HOME}/android-ndk-r27-canary" >> ${GITHUB_OUTPUT}